# Generated by Django 4.0.5 on 2022-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.IntegerField(max_length=3)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
