# Generated by Django 4.0.5 on 2022-06-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeoplesList', '0003_alter_person_options_remove_person_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='imc',
        ),
    ]
