# Generated by Django 4.0.5 on 2022-06-29 17:43

import AppPeoplesList.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeoplesList', '0007_alter_person_altura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-user']},
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=AppPeoplesList.models.upload_image_book),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
