# Generated by Django 4.0.5 on 2022-07-05 17:43

import AppPeoplesList.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPeoplesList', '0008_alter_person_options_person_image_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=AppPeoplesList.models.upload_image_book),
        ),
    ]
